name: 'Accessibility Checker'
# Verify accessibility on html files.
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  # Needed for the 'trilom/file-changes-action' action
  pull-requests: read

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  check-accessibility:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.x
          cache: npm

      - name: Install
        run: npm ci

      # Creates file "$/files.json"
      - name: Gather files changed
        id: file_changes
        uses: tj-actions/changed-files@v35
        with:
          json: "true"

      # For verification
      - name: Show files changed
        run: run: |
          for file in ${{ steps.file_changes.outputs.all_changed_files }}; do
            echo "$file was changed"
          done

      # This is where you can do your check, the list flag will have all of the
      # changed files. In the .js file you can filter out files that aren't
      # html/css files or whichever you don't want. Then you can run your
      # scanner to pull in colors or alt text and use the pure functions
      # to verify they pass accessibility
      - name: Accessibility Check
        env:
          FILES_CHANGED: ${{ steps.file_changes.outputs.all_changed_files }}
        run: node ./index.js